config/routes.rb
RbacDemo::Application.routes.draw do

  resources :home

  resources :users

  resources :accesses

  resources :roles

  resources :user_sessions

  match 'login' => "user_sessions#new",      :as => :login
  match 'logout' => "user_sessions#destroy", :as => :logout

  match 'accesses_roles' => "accesses_roles#accesses_roles_index", :as => 'accesses_roles'
  match 'accesses_roles_update' => "accesses_roles#update_accesses", :as => 'accesses_roles_update'

  match 'roles_users' => "roles_users#roles_users_index", :as => 'roles_users'
  match 'roles_users_update' => "roles_users#update_roles", :as => 'roles_users_update'

  match 'search_user_role_access' => "home#search_user_role_access", :as => 'search_user_role_access'
  match 'submit_search' => "home#submit_search", :as => 'submit_search'

  root :to => "user_sessions#new"

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :require_user

  def index
  end

  def search_user_role_access
    @users = User.all
    @results = []
    @users.each do |u|
      @results << [u.login,u.roles.map(&:name),u.roles.map(&:accesses).flatten.map(&:name).uniq]
    end
  end

  def submit_search
    @users = params[:user_id].present? ? User.all(:conditions => {:id => params[:user_id]}) : User.all
    @roles = params[:role_id].present? ? Role.all(:conditions => {:id => params[:role_id]}) : Role.all
    @accesses = params[:access_id].present? ? Access.all(:conditions => {:id => params[:access_id]}) : Access.all
    @results = []
    @users.reject!{|u| !u.roles.map(&:id).include?(@roles.first.id)} if @roles.size == 1
    @users.reject!{|u| !u.roles.map(&:accesses).flatten.map(&:id).include?(@accesses.first.id)} if @accesses.size == 1
    @users.each do |u|
      user_roles = u.roles.map(&:name)
      user_access = u.roles.map(&:accesses).flatten.map(&:name).uniq
      @results << [u.login,user_roles,user_access]
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper

  def fetch_options(model_name)

    model_name == User ? model_name.all.map{|u|[u.login,u.id]} : model_name.all.map{|u|[u.name,u.id]}
  end

end

app/views/home/_results.html.haml
%table.table
  %tr
    %th.text_align_center User
    %th.text_align_center Role
    %th.text_align_center Access
  - if @results.present?
    - @results.each do |r|
      %tr
        %td.text_align_center
          = r.first
        %td.text_align_center
          - r.second.each do |s|
            = s
            = r.second.last == s  ? "" : ","
            %br
        %td.text_align_center
          - r.last.each do |l|
            = l
            = r.last.last == l ? "" : ","
            %br
  - else
    %tr
      %td.text_align_center{:colspan => 3} No Record Found

app/views/home/index.html.haml
%h2 Welcome to RBAC Demo App

app/views/home/search_user_role_access.html.haml
%h3 Search User - Role - Access
%div#search_options
  = form_tag submit_search_path, :remote => true do
    = select_tag :user_id, options_for_select([["All Users",""]] + fetch_options(User))
    = select_tag :role_id,  options_for_select([["All Roles",""]] + fetch_options(Role))
    = select_tag :access_id, options_for_select([["All Accesses",""]] + fetch_options(Access))
    = submit_tag :go
%div#search_results
  = render :partial => "results"

app/views/home/submit_search.js.haml
$('#search_results').html("#{escape_javascript( render(:partial => 'results'))}");