config/routes.rb
RbacDemo::Application.routes.draw do

  resources :home

  resources :users

  resources :accesses

  resources :roles

  resources :user_sessions

  match 'login' => "user_sessions#new",      :as => :login
  match 'logout' => "user_sessions#destroy", :as => :logout

  match 'accesses_roles' => "accesses_roles#accesses_roles_index", :as => 'accesses_roles'
  match 'accesses_roles_update' => "accesses_roles#update_accesses", :as => 'accesses_roles_update'

  match 'roles_users' => "roles_users#roles_users_index", :as => 'roles_users'
  match 'roles_users_update' => "roles_users#update_roles", :as => 'roles_users_update'

  match 'search_user_role_access' => "home#search_user_role_access", :as => 'search_user_role_access'
  match 'submit_search' => "home#submit_search", :as => 'submit_search'

  root :to => "user_sessions#new"

end

app/controllers/accesses_controller.rb
class AccessesController < ApplicationController
  before_filter :require_user

  # GET /accesses
  # GET /accesses.json
  def index
    @accesses = Access.all
  end

  # GET /accesses/1
  # GET /accesses/1.json
  def show
    @access = Access.find(params[:id])
  end

  # GET /accesses/new
  # GET /accesses/new.json
  def new
    @access = Access.new
  end

  # GET /accesses/1/edit
  def edit
    @access = Access.find(params[:id])
  end

  # POST /accesses
  # POST /accesses.json
  def create
    @access = Access.new(params[:access])

    respond_to do |format|
      if @access.save
        format.html { redirect_to accesses_url, :notice=> 'Access was successfully created.' }
        format.json { render :json=> @access, :status=> :created, :location=> @access }
      else
        format.html { render :action=> "new" }
        format.json { render :json=> @access.errors, :status=> :unprocessable_entity }
      end
    end
  end

  # PUT /accesses/1
  # PUT /accesses/1.json
  def update
    @access = Access.find(params[:id])

    respond_to do |format|
      if @access.update_attributes(params[:access])
        format.html { redirect_to accesses_url, :notice=> 'Access was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action=> "edit" }
        format.json { render :json=> @access.errors, :status=> :unprocessable_entity }
      end
    end
  end

  # DELETE /accesses/1
  # DELETE /accesses/1.json
  def destroy
    @access = Access.find(params[:id])
    @access.destroy
    redirect_to accesses_url
  end
end

app/helpers/accesses_helper.rb
module AccessesHelper
end

app/views/accesses/_form.html.haml
= form_for @access do |f|
  - if @access.errors.any?
    #error_explanation
      %h2= "#{pluralize(@access.errors.count, "error")} prohibited this access from being saved:"
      %ul
        - @access.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .actions
    = f.submit @access.new_record? ? 'Save' : 'Update'

app/views/accesses/edit.html.haml
%h3 Editing Access

= render 'form'

= link_to 'Show', @access
\|
= link_to 'Back', accesses_path

app/views/accesses/index.html.haml
%h3 Access

%table.table
  %tr
    %th Name
    %th Action
    %th Action
    %th Action

  - @accesses.each do |access|
    %tr
      %td= access.name
      %td= link_to 'Show', access
      %td= link_to 'Edit', edit_access_path(access)
      %td= link_to 'Destroy', access, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'Add New Access', new_access_path

app/views/accesses/new.html.haml
%h3 Create New Access

= render 'form'

= link_to 'Back', accesses_path

app/views/accesses/show.html.haml
%p
  %b Name:
  = @access.name

= link_to 'Edit', edit_access_path(@access)
\|
= link_to 'Back', accesses_path