config/routes.rb
RbacDemo::Application.routes.draw do

  resources :home

  resources :users

  resources :accesses

  resources :roles

  resources :user_sessions

  match 'login' => "user_sessions#new",      :as => :login
  match 'logout' => "user_sessions#destroy", :as => :logout

  match 'accesses_roles' => "accesses_roles#accesses_roles_index", :as => 'accesses_roles'
  match 'accesses_roles_update' => "accesses_roles#update_accesses", :as => 'accesses_roles_update'

  match 'roles_users' => "roles_users#roles_users_index", :as => 'roles_users'
  match 'roles_users_update' => "roles_users#update_roles", :as => 'roles_users_update'

  match 'search_user_role_access' => "home#search_user_role_access", :as => 'search_user_role_access'
  match 'submit_search' => "home#submit_search", :as => 'submit_search'

  root :to => "user_sessions#new"

end

app/models/role.rb
class Role < ActiveRecord::Base
  attr_accessible :name
  has_and_belongs_to_many :accesses
  has_and_belongs_to_many :users
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  before_filter :require_user

  # GET /roles
  # GET /roles.json
  def index
    @roles = Role.all
  end

  # GET /roles/1
  # GET /roles/1.json
  def show
    @role = Role.find(params[:id])
  end

  # GET /roles/new
  # GET /roles/new.json
  def new
    @role = Role.new
  end

  # GET /roles/1/edit
  def edit
    @role = Role.find(params[:id])
  end

  # POST /roles
  # POST /roles.json
  def create
    @role = Role.new(params[:role])

    respond_to do |format|
      if @role.save
        format.html { redirect_to roles_url, :notice => 'Role was successfully created.' }
        format.json { render :json=> @role, :status => :created, :location=> @role }
      else
        format.html { render :action=> "new" }
        format.json { render :json=> @role.errors, :status=> :unprocessable_entity }
      end
    end
  end

  # PUT /roles/1
  # PUT /roles/1.json
  def update
    @role = Role.find(params[:id])

    respond_to do |format|
      if @role.update_attributes(params[:role])
        format.html { redirect_to roles_url, :notice=> 'Role was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action=> "edit" }
        format.json { render :json=> @role.errors, :status=> :unprocessable_entity }
      end
    end
  end

  # DELETE /roles/1
  # DELETE /roles/1.json
  def destroy
    @role = Role.find(params[:id])
    @role.destroy
    redirect_to roles_url
  end
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/views/roles/_form.html.haml
= form_for @role do |f|
  - if @role.errors.any?
    #error_explanation
      %h2= "#{pluralize(@role.errors.count, "error")} prohibited this role from being saved:"
      %ul
        - @role.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .actions
    = f.submit @role.new_record? ? 'Save' : 'Update'

app/views/roles/edit.html.haml
%h3 Editing role

= render 'form'

= link_to 'Show', @role
\|
= link_to 'Back', roles_path

app/views/roles/index.html.haml
%h3 Roles

%table.table
  %tr
    %th Name
    %th Action
    %th Action
    %th Action

  - @roles.each do |role|
    %tr
      %td= role.name
      %td= link_to 'Show', role
      %td= link_to 'Edit', edit_role_path(role)
      %td= link_to 'Destroy', role, :method => :delete, :data=> { :confirm=> 'Are you sure?' }

%br

= link_to 'Add New Role', new_role_path

app/views/roles/new.html.haml
%h3 Create New Role

= render 'form'

= link_to 'Back', roles_path

app/views/roles/show.html.haml
%p
  %b Name:
  = @role.name

= link_to 'Edit', edit_role_path(@role)
\|
= link_to 'Back', roles_path