config/routes.rb
RbacDemo::Application.routes.draw do

  resources :home

  resources :users

  resources :accesses

  resources :roles

  resources :user_sessions

  match 'login' => "user_sessions#new",      :as => :login
  match 'logout' => "user_sessions#destroy", :as => :logout

  match 'accesses_roles' => "accesses_roles#accesses_roles_index", :as => 'accesses_roles'
  match 'accesses_roles_update' => "accesses_roles#update_accesses", :as => 'accesses_roles_update'

  match 'roles_users' => "roles_users#roles_users_index", :as => 'roles_users'
  match 'roles_users_update' => "roles_users#update_roles", :as => 'roles_users_update'

  match 'search_user_role_access' => "home#search_user_role_access", :as => 'search_user_role_access'
  match 'submit_search' => "home#submit_search", :as => 'submit_search'

  root :to => "user_sessions#new"

end

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "RBAC"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    %link(href="images/apple-touch-icon-144x144.png" rel="apple-touch-icon-precomposed" sizes="144x144")
    %link(href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon-precomposed" sizes="114x114")
    %link(href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon-precomposed" sizes="72x72")
    %link(href="images/apple-touch-icon.png" rel="apple-touch-icon-precomposed")
    -#%link(href="images/favicon.ico" rel="shortcut icon")


  %body
    .navbar.navbar-fixed-top
      .navbar-inner
        .container
          %a.btn.btn-navbar(data-target=".nav-collapse" data-toggle="collapse")
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.brand(href="#{home_index_path}") RBAC
          .container.nav-collapse
            %ul.nav
              - if current_user
                %li= link_to "#{t :roles}", roles_path
                %li= link_to "#{t :accesses}", accesses_path
                %li= link_to "#{t :users}", users_path
                %li= link_to "#{t :manage_role_access}", accesses_roles_path
                %li= link_to "#{t :manage_user_roles}", roles_users_path
            %ul.nav{:style => "float:right;"}
              - if current_user
                %li= link_to "Welcome #{current_user.login}", edit_user_path(current_user)
                %li= link_to "#{t :sign_out}", logout_path
              - else
                %li= link_to "#{t :sign_in}", new_user_session_path
                %li= link_to "#{t :sign_up}", new_user_path
    .container.container_margin

      .row
        .span9
          = bootstrap_flash
          = yield
        - if current_user
          .span3
            .well.sidebar-nav
              %h3 Sidebar
              = link_to "Search User-Role-Access",search_user_role_access_path, :class => "search_link"

              %ul.nav.nav-list
                %li.nav-header Access Visibility
                - Access.all.each do |a|
                  %li= link_to a.name ,"#" if current_user.has_access?(a.id)
    
      %footer
        %p.text_align_center
          .created_by_div
            RBAC
    /
      Javascripts
      \==================================================
    / Placed at the end of the document so the pages load faster
    = javascript_include_tag "application"